# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1025)),
                ('file', models.FileField(null=True, upload_to='')),
                ('encryption_method', models.CharField(max_length=17)),
                ('compression_method', models.CharField(max_length=17)),
                ('loss_rate', models.FloatField()),
                ('compression_rate', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('decompressed', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
